import type { TransportRequestContent } from "./types";

export const transportRequestDe: TransportRequestContent = {
  badge: "Transport Anfrage",
  title: "Transport unverbindlich",
  highlight: "anfragen",
  intro:
    "Senden Sie uns Ihre Transportdaten für internationale Transporte, LTL, FTL, Palettenware, Projektlogistik oder Sondertransporte.\nUnser Team prüft Route, Transportart, Dokumente und besondere Anforderungen persönlich und meldet sich mit einer passenden Einschätzung.",

  steps: {
    transport: "Transportdaten",
    contact: "Kontaktdaten",
    summary: "Zusammenfassung",
  },

  shipmentTypes: {
    ltl: "Paletten & Pakete (LTL)",
    loadingMeters: "Lademeter eingeben",
    ftl: "Fahrzeugbuchung (FTL)",
  },

  packagingTypes: [
    "Palette",
    "Halbpalette",
    "Paket / Karton",
    "Gitterbox",
    "Holzkiste",
    "Sonstiges",
  ],

  destinationCountries: [
    "Kasachstan",
    "Usbekistan",
    "Kirgisistan",
    "Turkmenistan",
    "Tadschikistan",
    "Mongolei",
    "Aserbaidschan",
    "Georgien",
    "Armenien",
    "Irak",
    "Afghanistan",
    "Ukraine",
    "Sonstiges Land",
  ],

  europeanCountries: [
    "Deutschland",
    "Österreich",
    "Schweiz",
    "Belgien",
    "Bulgarien",
    "Dänemark",
    "Estland",
    "Finnland",
    "Frankreich",
    "Griechenland",
    "Irland",
    "Italien",
    "Kroatien",
    "Lettland",
    "Litauen",
    "Luxemburg",
    "Niederlande",
    "Norwegen",
    "Polen",
    "Portugal",
    "Rumänien",
    "Schweden",
    "Slowakei",
    "Slowenien",
    "Spanien",
    "Tschechien",
    "Ungarn",
    "Vereinigtes Königreich",
  ],

  vehicleTypes: [
    "Planen-LKW",
    "Koffer-LKW",
    "Kühlfahrzeug",
    "Mega-Trailer",
    "Sattelzug",
    "Sonstiges",
  ],

  temperatureOptions: [
    {
      value: "2-8",
      label: "+2°C bis +8°C",
    },
    {
      value: "15-25",
      label: "+15°C bis +25°C",
    },
  ],

  adrClasses: [
    {
      value: "2",
      label: "ADR-Klasse 2",
      description: "Gase (entzündbar, nicht entzündbar, giftig)",
    },
    {
      value: "3",
      label: "ADR-Klasse 3",
      description:
        "Entzündbare flüssige Stoffe, z. B. Benzin, Diesel oder Alkohole",
    },
    {
      value: "4",
      label: "ADR-Klasse 4",
      description:
        "Entzündbare feste Stoffe (4.1), selbstentzündliche Stoffe (4.2) und Stoffe, die bei Berührung mit Wasser entzündbare Gase entwickeln (4.3)",
    },
    {
      value: "5",
      label: "ADR-Klasse 5",
      description:
        "Entzündend bzw. oxidierend wirkende Stoffe (5.1) und organische Peroxide (5.2)",
    },
    {
      value: "6",
      label: "ADR-Klasse 6",
      description:
        "Giftige Stoffe (6.1) und ansteckungsgefährliche Stoffe (6.2)",
    },
    {
      value: "8",
      label: "ADR-Klasse 8",
      description: "Ätzende Stoffe wie Säuren oder Laugen",
    },
    {
      value: "9",
      label: "ADR-Klasse 9",
      description:
        "Verschiedene gefährliche Stoffe und Gegenstände, z. B. Lithiumbatterien, Asbest oder Trockeneis",
    },
  ],

  destinationCities: {
    Kasachstan: [
      "Almaty",
      "Astana",
      "Schymkent",
      "Aqtöbe",
      "Qaraghandy",
      "Taras",
      "Atyrau",
      "Öskemen",
      "Pawlodar",
      "Oral",
      "Qysylorda",
      "Semei",
      "Aqtau",
      "Qostanai",
      "Türkistan",
    ],
    Usbekistan: [
      "Taschkent",
      "Namangan",
      "Samarkand",
      "Andijon",
      "Nukus",
      "Fargʻona",
      "Qarshi",
      "Buchara",
      "Qoʻqon",
      "Margʻilon",
      "Jizzax",
      "Urganch",
      "Navoiy",
      "Termiz",
      "Angren",
    ],
    Kirgisistan: [
      "Bischkek",
      "Osch",
      "Dschalalabat",
      "Karakol",
      "Tokmok",
      "Kara-Balta",
      "Naryn",
      "Talas",
      "Batken",
      "Uzgen",
      "Balyktschy",
      "Kysyl-Kyja",
      "Isfana",
      "Kochkor-Ata",
      "Mailuu-Suu",
    ],
    Turkmenistan: [
      "Aşgabat",
      "Türkmenabat",
      "Daşoguz",
      "Mary",
      "Balkanabat",
      "Türkmenbaşy",
      "Bayramaly",
      "Tejen",
      "Abadan",
      "Köneürgenç",
      "Serdar",
      "Magdanly",
      "Bereket",
      "Kerki",
      "Gazojak",
    ],
    Tadschikistan: [
      "Duschanbe",
      "Chudschand",
      "Kulob",
      "Bokhtar",
      "Tursunsoda",
      "Isfara",
      "Panjakent",
      "Wahdat",
      "Konibodom",
      "Istarawschan",
      "Chorugh",
      "Hisor",
      "Danghara",
      "Buston",
      "Norak",
    ],
    Aserbaidschan: [
      "Baku",
      "Gəncə",
      "Sumqayıt",
      "Mingəçevir",
      "Lənkəran",
      "Şirvan",
      "Naxçıvan",
      "Şəki",
      "Yevlax",
      "Xankəndi",
      "Xaçmaz",
      "Salyan",
      "Quba",
      "Saatlı",
      "Sabirabad",
    ],
    Georgien: [
      "Tiflis",
      "Batumi",
      "Kutaisi",
      "Rustawi",
      "Gori",
      "Sugdidi",
      "Poti",
      "Telawi",
      "Achalziche",
      "Kutaissi",
      "Samtredia",
      "Marneuli",
      "Senaki",
      "Kaspi",
      "Bordschomi",
    ],
    Armenien: [
      "Jerewan",
      "Gjumri",
      "Wanadsor",
      "Abowjan",
      "Kapan",
      "Hrasdan",
      "Armawir",
      "Etschmiadsin",
      "Artaschat",
      "Ijevan",
      "Gawarr",
      "Charentsavan",
      "Masis",
      "Sisian",
      "Dilidschan",
    ],
    Mongolei: [
      "Ulaanbaatar",
      "Erdenet",
      "Darkhan",
      "Choir",
      "Ölgii",
      "Sainshand",
      "Choibalsan",
      "Mörön",
      "Dalandsadgad",
      "Arvaikheer",
      "Bayankhongor",
      "Uliastai",
      "Baruun-Urt",
      "Mandalgovi",
      "Altai",
    ],
    Irak: [
      "Bagdad",
      "Mossul",
      "Basra",
      "Erbil",
      "Kirkuk",
      "Nadschaf",
      "Kerbela",
      "Sulaymaniyah",
      "Nasiriyah",
      "Amara",
      "Ramadi",
      "Falludscha",
      "Dohuk",
      "Samarra",
      "Kut",
    ],
    Ukraine: [
      "Kyjiw",
      "Charkiw",
      "Odessa",
      "Dnipro",
      "Donezk",
      "Saporischschja",
      "Lwiw",
      "Krywyj Rih",
      "Mykolajiw",
      "Mariupol",
      "Luhansk",
      "Winnyzja",
      "Cherson",
      "Poltawa",
      "Tschernihiw",
    ],
  },

  labels: {
    pickupLocation: "Abholort in Europa",
    deliveryCountry: "Zustellland",
    destinationCity: "Zielstadt",
    shipmentType: "Wie wird die Ware versendet?",
    packagingType: "Verpackungsart",
    quantity: "Anzahl",
    length: "Länge cm",
    width: "Breite cm",
    height: "Höhe cm",
    weight: "Gewicht kg",
    loadingMeters: "Lademeter",
    goodsDescription: "Warenbeschreibung",
    vehicleType: "Fahrzeugtyp",
    pickupDate: "Gewünschtes Abholdatum",
    dangerousGoods: "Gefahrgut",
    temperatureControlled: "Temperaturgeführt",
    notes: "Besondere Hinweise",
    company: "Firma",
    contactPerson: "Ansprechpartner",
    email: "E-Mail",
    phone: "Telefon",
    country: "Land",
    message: "Nachricht",
    privacy: "Ich stimme zu, dass meine Angaben zur Bearbeitung der Anfrage verarbeitet werden.",
    yes: "Ja",
    no: "Nein",
    noneADR: "Kein Gefahrgut",
    noneThermo: "Kein Thermotransport",
    next: "Weiter",
    back: "Zurück",
    submit: "Anfrage absenden",
    addUnit: "Weitere Einheit hinzufügen",
    removeUnit: "Entfernen",
  },

  hints: {
    adrUnavailable:
      "ADR-Klasse 1 und ADR-Klasse 7 werden von GLOBALSPED nicht abgewickelt.",
    destinationCity:
      "Sie können eine Stadt aus der Vorschlagsliste wählen oder eine andere Zielstadt frei eingeben.",
    pickupLocation:
      "Sie können ein europäisches Land oder direkt einen konkreten Abholort eingeben.",
    temperatureControlled:
      "Bitte wählen Sie den benötigten Temperaturbereich, falls der Transport temperaturgeführt erfolgen soll.",
  },

  placeholders: {
    pickupLocation: "z. B. München, Deutschland",
    destinationCity: "z. B. Almaty",
    goodsDescription: "z. B. Maschinenbauteile, Handelsware, Ersatzteile",
    notes: "Zusätzliche Informationen zur Abholung, Ware oder Lieferung",
    company: "Ihre Firma",
    contactPerson: "Vorname Nachname",
    email: "name@firma.de",
    phone: "+49 ...",
    message: "Ihre Nachricht an GLOBALSPED",
  },

  summary: {
    title: "Ihre Transportübersicht",
    transportData: "Transportdaten",
    goodsData: "Warendaten",
    contactData: "Kontaktdaten",
    totalWeight: "Gesamtgewicht",
    totalVolume: "Gesamtvolumen",
    pieces: "Packstücke",
  },

  success: {
    title: "Anfrage versendet",
    text: "Vielen Dank. Ihre Transportanfrage wurde vorbereitet. Unser Team meldet sich schnellstmöglich bei Ihnen.",
    close: "Schließen",
  },

  validation: {
    requiredFields: "Bitte füllen Sie alle Pflichtfelder aus.",
    privacyRequired: "Bitte stimmen Sie der Verarbeitung Ihrer Angaben zu.",
  },
};