import type { TransportRequestContent } from "./types";

export const transportRequestEn: TransportRequestContent = {
  badge: "Transport Request",
  title: "Request transport",
  highlight: "without obligation",
  intro:
    "Send us your transport data for international transports, LTL, FTL, palletized goods, project logistics or special transports.\nOur team will personally review the route, transport type, documents and special requirements and get back to you with a suitable assessment.",

  steps: {
    transport: "Transport data",
    contact: "Contact details",
    summary: "Summary",
  },

  shipmentTypes: {
    ltl: "Pallets & parcels (LTL)",
    loadingMeters: "Enter loading meters",
    ftl: "Vehicle booking (FTL)",
  },

  packagingTypes: [
    "Pallet",
    "Half pallet",
    "Parcel / carton",
    "Pallet cage",
    "Wooden crate",
    "Other",
  ],

  destinationCountries: [
    "Kazakhstan",
    "Uzbekistan",
    "Kyrgyzstan",
    "Turkmenistan",
    "Tajikistan",
    "Mongolia",
    "Azerbaijan",
    "Georgia",
    "Armenia",
    "Iraq",
    "Afghanistan",
    "Ukraine",
    "Other country",
  ],

  europeanCountries: [
    "Germany",
    "Austria",
    "Switzerland",
    "Belgium",
    "Bulgaria",
    "Denmark",
    "Estonia",
    "Finland",
    "France",
    "Greece",
    "Ireland",
    "Italy",
    "Croatia",
    "Latvia",
    "Lithuania",
    "Luxembourg",
    "Netherlands",
    "Norway",
    "Poland",
    "Portugal",
    "Romania",
    "Sweden",
    "Slovakia",
    "Slovenia",
    "Spain",
    "Czech Republic",
    "Hungary",
    "United Kingdom",
  ],

  vehicleTypes: [
    "Curtainsider truck",
    "Box truck",
    "Refrigerated vehicle",
    "Mega trailer",
    "Semi-trailer truck",
    "Other",
  ],

  temperatureOptions: [
    {
      value: "2-8",
      label: "+2°C to +8°C",
    },
    {
      value: "15-25",
      label: "+15°C to +25°C",
    },
  ],

  packingGroups: [
    {
      value: "",
      label: "Please select",
    },
    {
      value: "I (X): High danger",
      label: "I (X): High danger",
    },
    {
      value: "II (Y): Medium danger",
      label: "II (Y): Medium danger",
    },
    {
      value: "III (Z): Low danger",
      label: "III (Z): Low danger",
    },
  ],

  limitedQuantityOptions: [
    {
      value: "Yes",
      label: "Yes",
    },
    {
      value: "No",
      label: "No",
    },
  ],

  adrClasses: [
    {
      value: "2",
      label: "ADR Class 2",
      description: "Gases, flammable, non-flammable or toxic",
    },
    {
      value: "3",
      label: "ADR Class 3",
      description:
        "Flammable liquids, e.g. petrol, diesel or alcohols",
    },
    {
      value: "4",
      label: "ADR Class 4",
      description:
        "Flammable solids (4.1), substances liable to spontaneous combustion (4.2) and substances which, in contact with water, emit flammable gases (4.3)",
    },
    {
      value: "5",
      label: "ADR Class 5",
      description:
        "Oxidizing substances (5.1) and organic peroxides (5.2)",
    },
    {
      value: "6",
      label: "ADR Class 6",
      description:
        "Toxic substances (6.1) and infectious substances (6.2)",
    },
    {
      value: "8",
      label: "ADR Class 8",
      description: "Corrosive substances such as acids or alkalis",
    },
    {
      value: "9",
      label: "ADR Class 9",
      description:
        "Miscellaneous dangerous substances and articles, e.g. lithium batteries, asbestos or dry ice",
    },
  ],

  destinationCities: {
    Kazakhstan: [
      "Almaty",
      "Astana",
      "Shymkent",
      "Aktobe",
      "Karaganda",
      "Taraz",
      "Atyrau",
      "Oskemen",
      "Pavlodar",
      "Oral",
      "Kyzylorda",
      "Semey",
      "Aktau",
      "Kostanay",
      "Turkistan",
    ],
    Uzbekistan: [
      "Tashkent",
      "Namangan",
      "Samarkand",
      "Andijan",
      "Nukus",
      "Fergana",
      "Qarshi",
      "Bukhara",
      "Kokand",
      "Margilan",
      "Jizzakh",
      "Urgench",
      "Navoiy",
      "Termez",
      "Angren",
    ],
    Kyrgyzstan: [
      "Bishkek",
      "Osh",
      "Jalal-Abad",
      "Karakol",
      "Tokmok",
      "Kara-Balta",
      "Naryn",
      "Talas",
      "Batken",
      "Uzgen",
      "Balykchy",
      "Kyzyl-Kiya",
      "Isfana",
      "Kochkor-Ata",
      "Mailuu-Suu",
    ],
    Turkmenistan: [
      "Ashgabat",
      "Turkmenabat",
      "Dashoguz",
      "Mary",
      "Balkanabat",
      "Turkmenbashi",
      "Bayramaly",
      "Tejen",
      "Abadan",
      "Koneurgench",
      "Serdar",
      "Magdanly",
      "Bereket",
      "Kerki",
      "Gazojak",
    ],
    Tajikistan: [
      "Dushanbe",
      "Khujand",
      "Kulob",
      "Bokhtar",
      "Tursunzoda",
      "Isfara",
      "Panjakent",
      "Vahdat",
      "Konibodom",
      "Istaravshan",
      "Khorugh",
      "Hisor",
      "Danghara",
      "Buston",
      "Nurek",
    ],
    Azerbaijan: [
      "Baku",
      "Ganja",
      "Sumgait",
      "Mingachevir",
      "Lankaran",
      "Shirvan",
      "Nakhchivan",
      "Sheki",
      "Yevlakh",
      "Khankendi",
      "Khachmaz",
      "Salyan",
      "Quba",
      "Saatli",
      "Sabirabad",
    ],
    Georgia: [
      "Tbilisi",
      "Batumi",
      "Kutaisi",
      "Rustavi",
      "Gori",
      "Zugdidi",
      "Poti",
      "Telavi",
      "Akhaltsikhe",
      "Kutaisi",
      "Samtredia",
      "Marneuli",
      "Senaki",
      "Kaspi",
      "Borjomi",
    ],
    Armenia: [
      "Yerevan",
      "Gyumri",
      "Vanadzor",
      "Abovyan",
      "Kapan",
      "Hrazdan",
      "Armavir",
      "Etchmiadzin",
      "Artashat",
      "Ijevan",
      "Gavar",
      "Charentsavan",
      "Masis",
      "Sisian",
      "Dilijan",
    ],
    Mongolia: [
      "Ulaanbaatar",
      "Erdenet",
      "Darkhan",
      "Choir",
      "Olgii",
      "Sainshand",
      "Choibalsan",
      "Moron",
      "Dalanzadgad",
      "Arvaikheer",
      "Bayankhongor",
      "Uliastai",
      "Baruun-Urt",
      "Mandalgovi",
      "Altai",
    ],
    Iraq: [
      "Baghdad",
      "Mosul",
      "Basra",
      "Erbil",
      "Kirkuk",
      "Najaf",
      "Karbala",
      "Sulaymaniyah",
      "Nasiriyah",
      "Amarah",
      "Ramadi",
      "Fallujah",
      "Duhok",
      "Samarra",
      "Kut",
    ],
    Ukraine: [
      "Kyiv",
      "Kharkiv",
      "Odesa",
      "Dnipro",
      "Donetsk",
      "Zaporizhzhia",
      "Lviv",
      "Kryvyi Rih",
      "Mykolaiv",
      "Mariupol",
      "Luhansk",
      "Vinnytsia",
      "Kherson",
      "Poltava",
      "Chernihiv",
    ],
  },

  labels: {
    pickupLocation: "Pickup location in Europe",
    deliveryCountry: "Destination country",
    destinationCity: "Destination city",
    pleaseSelect: "Please select",
    destinationCitySelectPlaceholder: "Select destination city",
    destinationCitySelectCountryFirst: "Select destination country first",
    shipmentType: "How will the goods be shipped?",
    packagingType: "Packaging type",
    quantity: "Quantity",
    length: "Length cm",
    width: "Width cm",
    height: "Height cm",
    weight: "Weight kg",
    loadingMeters: "Loading meters",
    goodsDescription: "Goods description",
    vehicleType: "Vehicle type",
    pickupDate: "Desired pickup date",
    dangerousGoods: "Dangerous goods",
    unNumber: "UN number",
    packingGroup: "Packing group",
    adrPoints: "ADR under 1000 points",
    limitedQuantity: "Limited Quantity",
    temperatureControlled: "Temperature-controlled",
    notes: "Special instructions",
    company: "Company",
    contactPerson: "Contact person",
    email: "Email",
    phone: "Phone",
    country: "Country",
    message: "Message",
    privacy:
      "I agree that my information may be processed for the purpose of handling this request.",
    yes: "Yes",
    no: "No",
    noneADR: "No dangerous goods",
    noneThermo: "No temperature-controlled transport",
    next: "Next",
    back: "Back",
    submit: "Submit request",
    addUnit: "Add another unit",
    removeUnit: "Remove",
    standardDocs: "Upload goods documents / images",
    adrDocs: "Upload ADR documents",
    removeFile: "Remove file",
  },

  hints: {
    adrUnavailable:
      "ADR Class 1 and ADR Class 7 are not handled by GLOBALSPED.",
    destinationCity:
      "You can select a city from the suggestion list or freely enter another destination city.",
    pickupLocation:
      "You can enter a European country or a specific pickup location directly.",
    temperatureControlled:
      "Please select the required temperature range if the transport needs to be temperature-controlled.",
    standardDocs:
      "Optional: e.g. goods documents, photos of the goods, packing lists or technical documents.",
    adrDocs:
      "Optional: e.g. safety data sheet, ADR documents or dangerous goods documents.",
    uploadFormats:
      "Allowed formats are PDF, JPG, PNG, DOC and DOCX. Maximum total size: 10 MB.",
  },

  placeholders: {
    pickupLocation: "e.g. Munich, Germany",
    destinationCity: "e.g. Almaty",
    goodsDescription: "e.g. mechanical components, commercial goods, spare parts",
    unNumber: "e.g. UN 1203",
    adrPoints: "max. 1000",
    limitedQuantity: "e.g. LQ according to ADR or quantity per inner packaging",
    notes: "Additional information about pickup, goods or delivery",
    company: "Your company",
    contactPerson: "First name Last name",
    email: "name@company.com",
    phone: "+49 ...",
    message: "Your message to GLOBALSPED",
  },

  summary: {
    title: "Your transport overview",
    transportData: "Transport data",
    goodsData: "Goods data",
    contactData: "Contact details",
    totalWeight: "Total weight",
    totalVolume: "Total volume",
    pieces: "Packages",
    unNumber: "UN number",
    adrPoints: "ADR under 1000 points",
    limitedQuantity: "Limited Quantity",
  },

  success: {
    title: "Request submitted",
    text: "Thank you. Your transport request has been prepared. Our team will get back to you as soon as possible.",
    close: "Close",
  },

  validation: {
    requiredFields: "Please complete all required fields.",
    privacyRequired: "Please agree to the processing of your information.",
    fileType: "Please upload only files in PDF, JPG, PNG, DOC or DOCX format.",
    fileSize: "The selected files may not exceed a total size of 10 MB.",
    submitError:
      "The request could not be sent. Please try again or contact us directly by email.",
  },
};